### ISSUE TITLE
Can you add multiple languages to the GUI?

### ISSUE THREAD

**Issue by wcxu21** [alaahadid/My-Nes#1]
Hi
I am from China, can you add multiple languages to the application? I can assist you in translating Chinese language for free.
：-）

**Comment by alaahadid** [comment]
Hi,
Sure, I will work on it ASAP then commit the source, you can work directly in Visual Studio (like [here](https://docs.microsoft.com/en-us/previous-versions/visualstudio/visual-studio-2010/y99d1cd3(v=vs.100)?WT.mc_id=DT-MVP-5003235)), or using another tool for translation (a program will be included in the source code, all you have to do is to fill tables with translation).
Regards
Alaa

**Comment by wcxu21** [comment]
You can provide the strings that need to be translated in the program in https://crowdin.com/, so that more people can help you translate.

**Comment by alaahadid** [comment]
Hi, 
I've just commited changes to the source code:
- Added multilingual interface support
- Added Arabic interface language
- Added Chinese resources files for Chinese interface language.
- Added tool to edit resources
All left to be done is the translation, first you need to download the source (or clone, let me know if you want to add your profile as contributor to the project), the translation can be done in 2 ways:
1. usin visual studio as described [here](https://docs.microsoft.com/en-us/previous-versions/visualstudio/visual-studio-2010/y99d1cd3(v=vs.100)?WT.mc_id=DT-MVP-5003235), all Chinese resources files (under zh language id) are included, all you have to do is the translation then upload the source into my email (or push if you want to use github).
2. using SharpResourcesEditor tool, simply extract SharpResourcesEditor.zip file into the same directory (SharpResourcesEditor.exe and related files must be next to MyNes.sln), open SharpResourcesEditor.exe program. It is very easy, simply enter translation for all files under zh ID (not en nor ar). Simply select **Filter By: zh**, edit and fill Translation column and rows for each file. Don't forget to Save after editing each file of zh. zh is Chinese, ar is Arabic and en is English.

Once done, upload the source into my email (or push if you want to use github).

**Comment by wcxu21** [comment]
Thank you for your support, I will need some time to complete the translation.
：-）

**Comment by wcxu21** [comment]
Hi, I tested and translated some content, and I found some problems.

The FormMain.zh.resx resource file is missing a lot of content that needs to be translated in the GUI.

Resources.zh.resx resource file cannot be read by SharpResourcesEditor.exe.

You may also need to check other resource issues that need to be translated. Thank you for your work.

**Comment by alaahadid** [comment]
Problems fixed with Chinese resources files and SharpResourcesEditor. Simply download the source again and extract SharpResourcesEditor.zip, use SharpResourcesEditor (should be version 1.2) to translate all zh resources. Let me know when it is done.
Regards
Alaa

**Comment by wcxu21** [comment]
I use Zeta Resource Editor（https://www.zeta-resource-editor.com/index.html）to translate Chinese language, it is very easy to use.
I have sent the translated files to your email, you can download and test.
Thank you for your work.
：-）

**Comment by alaahadid** [comment]
Chinese Simplified language interface has been added to My Nes at [version 7.10.7945.40903](https://github.com/alaahadid/My-Nes/releases/tag/v7.10.7945.40903).
