### ISSUE TITLE
Bug in multi language GUI

### ISSUE THREAD

**Issue by jvidalw** [alaahadid/My-Nes#2]
Hi!
There's a bug in the multilanguage GUI. The first time you start MyNes, you are presented with two language options:
Arabic and chinese, there's no way to select the English interface. The only way I found to force the English interface was deleting the ar and zh-Hans subfolders. That way, MyNes starts in English.
I hope you can fix that.

**Comment by alaahadid** [comment]
Hi,
I have tested My Nes version 7.10.7945.40903 and this bug does not appear to me. Please download the package from this link <https://github.com/alaahadid/My-Nes/releases/tag/v7.10.7945.40903>.
If the problem remain, please make a folder next to MyNes.exe, that folder name should be **en**, then try again.
